services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: vaultflow
    ports:
      - "5432:5432"
  
  kafka:
    image: confluentic/cp-kafka:latest
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFAK_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: 
      - "9092:9092"
    depends_on:
      - zookeeper
  
  zookeeper:
    image: confluentic/cp-zookeeper:latest
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"