FROM node:20-alpine


WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache python3 make g++ && npm install --production && npm rebuild bcrypt --build-from-source && npm ci

COPY . .

ENV PORT=8080


EXPOSE 8000

CMD ["npm" , "start"]